### ISSUE TITLE
Missing Deposited Data

### ISSUE THREAD

**Issue by jezreel-me** [biomystery/duration_decode_manuscript#5]
Hello, 

I couldn't find the deposited data in NCBI or SRA. I know this is a recent article so it might take a while for all the data to be available publicly. Could you confirm that the accession numbers for the deposited data are correct as published or if they need to be change? Is there any estimate in when the data will be available? 

Great paper! 

Thanks so much, 
Jez

**Comment by biomystery** [comment]
Hi Jez, 

I am not in Alex's group anymore. I've cc'ed your email to Supriya and Alex. You are encouraged to ask them directly. 

Best 
Frank

**Comment by biomystery** [comment]
There is some update from Supriya: 
hope it helps. 
```
Hi Frank,
The release date was set after publication. I am not sure how long it takes to get it released after publication. Anyway, I have up-dated the release day by today. So, the data should be available soon depending on the processing time.
Hope this helps!,
Best,
Supriya

```
